[project]
name = "systems-status-monitor-redux"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HelloMorrisMoss", email = "56200569+HelloMorrisMoss@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.129.0",
    "httpx>=0.28.1",
    "jinja2==3.1.4",
    "paramiko==3.4.0",
    "pydantic==2.12.5",
    "pytest==8.0.2",
    "uvicorn==0.29.0",
    "starlette==0.52.1",
]

[project.scripts]
systems-status-monitor-redux = "systems_status_monitor_redux.main:start_server"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src/systems_status_monitor_redux"]